### ISSUE TITLE
Not normalizing test data

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [laur1s/DeepPreprocess#11]
The way the current normalization function is working, it is not normalizing the test data since it uses the same mean/std values it got from the training dataset.

**Comment by laur1s** [comment]
I am not an expert in machine learning but all the literature I read uses mean and std values from the training dataset. [1](https://stats.stackexchange.com/questions/77350/perform-feature-normalization-before-or-within-model-validation). Reasoning behind this approach is that test data is supposed to be "unseen" therefore you can't use mean/ std values from it.

If you think that this approach is wrong please comment here :)

**Comment by BrunoGomesCoelho** [comment]
You're right, it does indeed seem to be the recommended approach and I can see why now. You learn something new every day, my bad.
