### ISSUE TITLE
Pep8

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [laur1s/DeepPreprocess#6]
I see that the code does not seem to follow pep8, what would you think of porting the current code to it?
More information about pep8, the suggested guidelines for python: [pep8 information](https://www.quora.com/Why-is-PEP-8-considered-to-be-so-important)

**Comment by laur1s** [comment]
Hi, thanks for reviewing the code and helping out! I agree, pep8 is a good practice and should be followed.

**Comment by BrunoGomesCoelho** [comment]
Cool, will port the existing code!
